### ISSUE TITLE
Typo in life-cycle model

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/IntroToLifeCycleModels#1]
I was reading Section 5.1 of the intro to life-cycle about portfolio choice model with risky assets and the budget constraint is not consistent with the code

In the doc, the budget constraint reads as 

c+aprime = (1+r)*a + labor_income

but in the code (Example 31) the term (1+r) is absent. My understanding is that the version in the code is the correct one.

**Comment by robertdkirkby** [comment]
you are quite right. fixed. thanks.
