### ISSUE TITLE
Life cycle model A5

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/IntroToLifeCycleModels#3]
Hi Rob, 
I was running the script LifeCycleModelA5 and I got the following warning:

Warning: LifeCycleProfiles_FHorz_Case1 has changed the order of the fourth and fifth inputs (should now be
something like Params,[] when previously it would have been [],Params) 

The age conditional statistics should be updated to the new order of parameters

**Comment by robertdkirkby** [comment]
Thanks. Fixed (needed to make same fix to essentially all the appendix models; actually I need to overhaul the whole appendix about shocks because there are now better ways to handle all this).
