### ISSUE TITLE
LifeCycleModel28

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/IntroToLifeCycleModels#4]
In life cycle model 28, dual earners model, the state variables are (a,z1,z2,e1,e2,j), so the part below is not correct:

% V is now (a,z1,z2,j). One dimension for each state variable.
% Compare
size(V)
% with
[n_a,n_z(1),n_z(2),N_j]

Actually (e1,e2) are purely iid so I think that if we used the cash-on-hand trick they could be dropped from the set of state variables, but the toolkit uses a simpler approach.

**Comment by robertdkirkby** [comment]
Cleaned this up.
