### ISSUE TITLE
Why my issues were removed?

### ISSUE THREAD

**Issue by kingarthur72** [vfitoolkit/IntroToLifeCycleModels#6]
I have posted about 10 or 11 issues with respect to the programs about portfolio choices.

They are all gone. What happened? Thanks.

**Comment by robertdkirkby** [comment]
I commented on them and closed them. (Some fixes were pushed as part of addressing them.)

Note: you left the issues on VFI Toolkit, not on the Intro to Life-Cycles, which is where this issue is:
https://github.com/vfitoolkit/VFIToolkit-matlab/issues?q=is%3Aissue+is%3Aclosed

**Comment by robertdkirkby** [comment]
I am leaving this open for now to make sure you see it, but I will close it sometime in Nov if there is no further activity.

**Comment by robertdkirkby** [comment]
PS. I think Github should have sent you notifications when I closed your issues. Notifications is the mailbox icon near top right of github website, there is a blue dot on it when you have unread notifications.

**Comment by kingarthur72** [comment]
Good evening, Robert,

I really appreciate that you share the code with us; and I am especially
grateful because all programs are clearly written. Of course, the issues I
raised are just tiny things. And you can, of course, close my comments
(sorry that I did not find them when I asked again and I do see
your replies).

Will update the model files (as you suggested) and re-run them. Will update
you about what I get.

Thanks again

Arthur

**Comment by robertdkirkby** [comment]
All good.

Honestly, I myself had to do a search to figure out how to see closed issues :)

**Comment by robertdkirkby** [comment]
Often it can be easier to ask questions/give feedback via the forum:
http://discourse.vfitoolkit.com/

Rather than via Github.

**Comment by kingarthur72** [comment]
Good morning, Robert,

Just got some time to re-run the programs you have provided on Github.

I downloaded the VFIToolkit-matlab-master.zip from
https://github.com/vfitoolkit/VFIToolkit-matlab (so the files have been
updated); and installed the VFIToolkit on my computer.

I downloaded the IntroToLifeCycleModels-main.zip from
https://github.com/vfitoolkit/IntroToLifeCycleModels (so the files have
been updated); and put all files on my computer.

I run m-files for these models; and the results are presented in the
attached PDF files.

There are still mistakes. Would you please check for that?

Thanks and all the best.

Arthur

**Comment by robertdkirkby** [comment]
The pdf did not get included. Please either just email me directly robertdkirkby@gmail.com, or better still, use the forum: http://discourse.vfitoolkit.com/

**Comment by kingarthur72** [comment]
Here they are

**Comment by kingarthur72** [comment]
These files do not require log in.

**Comment by kingarthur72** [comment]
Then forget about these links.

The files are attached to this email.

**Comment by kingarthur72** [comment]
Thank you
