### ISSUE TITLE
Lifecyclemodel20

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/IntroToLifeCycleModels#7]
The comment
jequaloneDist(1,:)=statdist_z; % All agents start with zero assets, and the median shock

Is not correct  since agents start from the long run distrib of z, not from the median shock

**Comment by aledinola** [comment]
Also, line 160-161 the comment says the model is deterministic but this model has shocks

**Comment by robertdkirkby** [comment]
fixed, thanks!
https://github.com/vfitoolkit/IntroToLifeCycleModels/commit/7274b5ca32f50a64a7cc54ff325b2b87d485f979
